namespace PracticeTheVerb.Domain.Entities.Italian;

public class ItalianVerb : BaseEntity
{
	public string infinitivopresente { get; set; }
	public string infinitivopassato { get; set; }
	public string participiopresente { get; set; }
	public string participiopassato { get; set; }
	public string gerundiopresente { get; set; }
	public string gerundiopassato { get; set; }
	public string indicativopresenteio { get; set; }
	public string indicativopresentetu { get; set; }
	public string indicativopresentelui { get; set; }
	public string indicativopresentenoi { get; set; }
	public string indicativopresentevoi { get; set; }
	public string indicativopresenteloro { get; set; }
	public string indicativopassatoprossimoio { get; set; }
	public string indicativopassatoprossimotu { get; set; }
	public string indicativopassatoprossimolui { get; set; }
	public string indicativopassatoprossimonoi { get; set; }
	public string indicativopassatoprossimovoi { get; set; }
	public string indicativopassatoprossimoloro { get; set; }
	public string indicativoimperfettoio { get; set; }
	public string indicativoimperfettotu { get; set; }
	public string indicativoimperfettolui { get; set; }
	public string indicativoimperfettonoi { get; set; }
	public string indicativoimperfettovoi { get; set; }
	public string indicativoimperfettoloro { get; set; }
	public string indicativotrapassatoprossimoio { get; set; }
	public string indicativotrapassatoprossimotu { get; set; }
	public string indicativotrapassatoprossimolui { get; set; }
	public string indicativotrapassatoprossimonoi { get; set; }
	public string indicativotrapassatoprossimovoi { get; set; }
	public string indicativotrapassatoprossimoloro { get; set; }
	public string indicativopassatoremotoio { get; set; }
	public string indicativopassatoremototu { get; set; }
	public string indicativopassatoremotolui { get; set; }
	public string indicativopassatoremotonoi { get; set; }
	public string indicativopassatoremotovoi { get; set; }
	public string indicativopassatoremotoloro { get; set; }
	public string indicativotrapassatoremotoio { get; set; }
	public string indicativotrapassatoremototu { get; set; }
	public string indicativotrapassatoremotolui { get; set; }
	public string indicativotrapassatoremotonoi { get; set; }
	public string indicativotrapassatoremotovoi { get; set; }
	public string indicativotrapassatoremotoloro { get; set; }
	public string indicativofuturosempliceio { get; set; }
	public string indicativofuturosemplicetu { get; set; }
	public string indicativofuturosemplicelui { get; set; }
	public string indicativofuturosemplicenoi { get; set; }
	public string indicativofuturosemplicevoi { get; set; }
	public string indicativofuturosempliceloro { get; set; }
	public string indicativofuturoanterioreio { get; set; }
	public string indicativofuturoanterioretu { get; set; }
	public string indicativofuturoanteriorelui { get; set; }
	public string indicativofuturoanteriorenoi { get; set; }
	public string indicativofuturoanteriorevoi { get; set; }
	public string indicativofuturoanterioreloro { get; set; }
	public string congiuntivopresenteio { get; set; }
	public string congiuntivopresentetu { get; set; }
	public string congiuntivopresentelui { get; set; }
	public string congiuntivopresentenoi { get; set; }
	public string congiuntivopresentevoi { get; set; }
	public string congiuntivopresenteloro { get; set; }
	public string congiuntivopassatoio { get; set; }
	public string congiuntivopassatotu { get; set; }
	public string congiuntivopassatolui { get; set; }
	public string congiuntivopassatonoi { get; set; }
	public string congiuntivopassatovoi { get; set; }
	public string congiuntivopassatoloro { get; set; }
	public string congiuntivoimperfettoio { get; set; }
	public string congiuntivoimperfettotu { get; set; }
	public string congiuntivoimperfettolui { get; set; }
	public string congiuntivoimperfettonoi { get; set; }
	public string congiuntivoimperfettovoi { get; set; }
	public string congiuntivoimperfettoloro { get; set; }
	public string congiuntivotrapassatoio { get; set; }
	public string congiuntivotrapassatotu { get; set; }
	public string congiuntivotrapassatolui { get; set; }
	public string congiuntivotrapassatonoi { get; set; }
	public string congiuntivotrapassatovoi { get; set; }
	public string congiuntivotrapassatoloro { get; set; }
	public string imperativopresentetu { get; set; }
	public string imperativopresentelui { get; set; }
	public string imperativopresentenoi { get; set; }
	public string imperativopresentevoi { get; set; }
	public string imperativopresenteloro { get; set; }
}
